openapi: 3.0.0
info:
  version: "0.0.3-unstable"
  title: VC API
  description: This is an Experimental Open API Specification for the [VC Data Model](https://www.w3.org/TR/vc-data-model/).
  license:
    name: W3C Software and Document License
    url: http://www.w3.org/Consortium/Legal/copyright-software.
  contact:
    name: GitHub Source Code
    url: https://github.com/w3c/vcalm
paths:
components:
  schemas:
    VerifiablePresentation:
      type: object
      description: A JSON-LD Verifiable Presentation with a proof.
      properties:
        "@context":
          type: array
          description: The JSON-LD context of the presentation. Each item in the @context array MUST be a string.
          items:
            type: string
        "type":
          type: array
          description: The JSON-LD type of the presentation. Each item in the type array MUST be a string.
          items:
            type: string
      example:
        {
          "@context":
            [
              "https://www.w3.org/ns/credentials/v2",
              "https://www.w3.org/ns/credentials/examples/v2",
            ],
          "type": ["VerifiablePresentation"],
        }
